import ispit
import matplotlib.pyplot as plt
p1 = ispit.Bullet()
p1.init(2,100,0.01)
x,y,t,vx,vy = p1.tijek_dogadanja()
plt.plot(x,y)
plt.xlabel("x [m]")
plt.ylabel("y [m]")
plt.title("x,y graf")
plt.show()
plt.plot(t,x)
plt.xlabel("Vrijeme [s]")
plt.ylabel("x [m]")
plt.title("x,t graf")
plt.show()
plt.plot(t,y)
plt.xlabel("Vrijeme [s]")
plt.ylabel("y [m]")
plt.title("y,t graf")
plt.show()
p1.reset()

#bolje izgleda s dt = 0.001 s

p2 = ispit.Bullet()
p2.init(2,100,0.001)
x1,y1,t1,vx1,vy1 = p2.tijek_dogadanja()
plt.plot(x1,y1)
plt.xlabel("x [m]")
plt.ylabel("y [m]")
plt.title("x,y graf")
plt.show()
plt.plot(t1,x1)
plt.xlabel("Vrijeme [s]")
plt.ylabel("x [m]")
plt.title("x,t graf")
plt.show()
plt.plot(t1,y1)
plt.xlabel("Vrijeme [s]")
plt.ylabel("y [m]")
plt.title("y,t graf")
plt.show()
p1.reset()
