import matplotlib.pyplot as plt
import bungeejumping as bj
p1 = bj.BungeeJumping(200,50,50,30)
p2 = bj.BungeeJumping(200,50,50,30,1.22,1,0.1,True)
p1.move(100,0.01)
p2.move(100,0.01)
plt.plot(p1.t, p1.y)
plt.xlabel("t [s]")
plt.ylabel("y [m]")
plt.title("Ovisnost položaja o vremenu")
plt.show()
plt.plot(p1.t, p1.Ek, label ="Kinetička energija")
plt.plot(p1.t, p1.Egp, label ="Gravitacijska potencijalna energija")
plt.plot(p1.t, p1.Eep, label = "Elastična potencijalna energija")
plt.plot(p1.t, p1.E, label ="Ukupna energija")
plt.xlabel("t [s]")
plt.ylabel("E [J]")
plt.title("Ovisnost mehaničke energije o vremenu")
plt.show()
plt.plot(p2.t, p2.y)
plt.xlabel("t [s]")
plt.ylabel("y [m]")
plt.title("Ovisnost položaja o vremenu")
plt.show()
plt.plot(p2.t, p2.Ek)
plt.plot(p2.t, p2.Egp)
plt.plot(p2.t, p2.Eep)
plt.plot(p2.t, p2.E)
plt.xlabel("t [s]")
plt.ylabel("E [J]")
plt.title("Ovisnost mehaničke energije o vremenu")
plt.show()
